apiVersion: v1
kind: Service
metadata:
  name: sagemaker-fastapi-svc
spec:
  selector:
    app: sagemaker-fastapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
